### ISSUE TITLE
CMakeLists.txt outdated

### ISSUE THREAD

**Issue by lurr** [Protryon/Basin#33]
many source files missing

**Comment by Protryon** [comment]
Ecx added it and no longer has time to maintain it. I deleted it.

**Comment by rcx** [comment]
U wanna bet

**Comment by Protryon** [comment]
@ecx86 If you wanna maintain things, be my guest. :)

**Comment by Lignum** [comment]
Can't you just do this? No need to maintain the file list.
```CMake
file(GLOB_RECURSE SOURCE_FILES "basin/src/*.c")
```

**Comment by rcx** [comment]
@Lignum [I don't believe in globbing](https://stackoverflow.com/questions/1027247/specify-source-files-globally-with-glob/1060061), but anyways I have updated the build scripts.
