### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by FiLip2201** [Protryon/Basin#35]
Hi, I have problem with compiling. Can you help me? (I'm real newbie)
`filip@DESKTOP-95MTGSV MINGW64 /d/Desktop/Basin1 (master)
$ cd basin/Debug; make
Building file: ../src/accept.c
Invoking: GCC C Compiler
cc  -std=gnu11 -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/accept.d" -MT"src/accept.d" -o "src/accept.o" "../src/accept.c"
/bin/sh: cc: command not found
make: *** [src/accept.o] Error 127`

**Comment by Protryon** [comment]
You don't have GCC installed on your system it seems, install it along with all of the dependencies for basin. I recommend installing the `build-essentials` Ubuntu package.

**Comment by rcx** [comment]
You seem to be on mingw. Use `pacman -S gcc` to install gcc. You also will need to install the headers (-dev) packages for the relevant libraries Basin uses as well, probably libssl, libpthread, and a few others that aren't coming to mind right now.
